### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Pandademic** [Pandademic/dotfiles#1]
- [ ] use `dunst`
- [x] recompile `awesome` to `v4.3-git`
- [ ] use `shkd` more to have wm-agnostic keybinds
- [ ] add windows to `tsdmrc`
